name: Sync and Merge

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --local user.email "shuohao@126.com"
          git config --local user.name "shuohao"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/suxuang/myIPTV.git
          git fetch upstream
          git checkout main
          git merge upstream/main -X theirs --allow-unrelated-histories || true
          git add.
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto-merged with upstream/main using theirs strategy"
          fi
          
      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "push"
            git push -f origin main
          else
            echo "No changes to commit and push, skipping this step."
          fi
